server:
  address: ":8080"
  mode: "debug"
  cors:
    allowed_origins: ["http://localhost:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
    allow_credentials: true

database:
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    dbname: "archery_training"
    sslmode: "disable"
    max_open_conns: 20
    max_idle_conns: 5
    conn_max_lifetime: "1h"
  
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5

jwt:
  secret: "your-secret-key"
  expires_in: "24h"

upload:
  path: "./uploads"
  max_size: 10485760  # 10MB
  allowed_types: ["video/mp4", "video/quicktime"]

ai_service:
  url: "http://localhost:5000"
  timeout: "30s"
  max_retries: 3
  endpoints:
    pose_analysis: "/analyze/pose"
    target_analysis: "/analyze/target"

video:
  temp_dir: "./temp"
  frame_rate: 30
  quality: "medium"
  max_duration: 300  # 5分钟

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  ping_period: "30s"
  pong_wait: "60s"

log:
  level: "debug"
  file: "logs/app.log"
  format: "json"
  max_size: 100    # MB
  max_age: 7       # 天
  max_backups: 5   # 备份文件数
  compress: true 